### ISSUE TITLE
[BUG] - fatal: repository 'https://github.com/veeso/homebrew-bitpanda730/' not found

### ISSUE THREAD

**Issue by michelemancusi** [veeso/bitpanda730#1]
When trying to install it on macOS Ventura 13.2, I obtain the following:

Cloning into '/usr/local/Homebrew/Library/Taps/veeso/homebrew-bitpanda730'...
remote: Repository not found.
fatal: repository 'https://github.com/veeso/homebrew-bitpanda730/' not found
Error: Failure while executing; `git clone https://github.com/veeso/homebrew-bitpanda730 /usr/local/Homebrew/Library/Taps/veeso/homebrew-bitpanda730 --origin=origin --template=` exited with 128.

**Comment by veeso** [comment]
I haven't finished working on it yet.
I've paused the development for a while since it's still not the tax declaration period.

I will resume working on it soon

**Comment by michelemancusi** [comment]
ok perfect, thanks!
